#!/bin/bash

INTERPRETER=php
if [ -f ./composer.json ]; then
    COMPOSER_PHP_VERSION=`grep '"php"' composer.json | sed -ne 's/^.*"[^0-9]*\([0-9]\.[0-9]\).*".*/\1/p'`
    INTERPRETER=php$COMPOSER_PHP_VERSION
fi

$INTERPRETER "$@"
