#!/bin/bash

CONSOLE_PATHS=('bin/console' 'app/console')

for CONSOLE_ELEM in "${CONSOLE_PATHS[@]}"
do
    if [ -f "$CONSOLE_ELEM" ]; then
        CONSOLE_PATH=$CONSOLE_ELEM
        break
    fi
done

if [ -z "$CONSOLE_PATH" ]; then
    echo "Symfony console not found"
    exit
fi

./php+ "$CONSOLE_PATH" "$@"
